package com.gmail.jpk.stu.sprites;

public enum SpriteType {
	MINIMAP_ICON, PLAYERSHIP, SPACESHIP, MAP_ICON, WEAPON_SPRITE, 
	SPACE_OBJECT, HOMEWORLD, MOON, STAR, ASTEROID, ASTEROID_ICON,
	TALENT_ICON;
}
